//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _9_07_2023_Planner.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_9_07_2023_Planner.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на + Add Group.
        /// </summary>
        internal static string AddGroupButton {
            get {
                return ResourceManager.GetString("AddGroupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose color of new group :.
        /// </summary>
        internal static string AddGroupWindowText_ChooseColor {
            get {
                return ResourceManager.GetString("AddGroupWindowText_ChooseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter New Group Name :.
        /// </summary>
        internal static string AddGroupWindowText_EnterGroupName {
            get {
                return ResourceManager.GetString("AddGroupWindowText_EnterGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Planner Application.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language will change after restart application.
        /// </summary>
        internal static string ChangeLanguageMessage {
            get {
                return ResourceManager.GetString("ChangeLanguageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change Language.
        /// </summary>
        internal static string ChangeLanguageWindowTitle {
            get {
                return ResourceManager.GetString("ChangeLanguageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !!! Task Completed !!!.
        /// </summary>
        internal static string CompletedTaskString {
            get {
                return ResourceManager.GetString("CompletedTaskString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complete Task.
        /// </summary>
        internal static string CompleteTaskButton {
            get {
                return ResourceManager.GetString("CompleteTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на + Create Task.
        /// </summary>
        internal static string CreateTaskButton {
            get {
                return ResourceManager.GetString("CreateTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Should delete group within all tasks?.
        /// </summary>
        internal static string DeleteGroupRequest {
            get {
                return ResourceManager.GetString("DeleteGroupRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EnterHeader....
        /// </summary>
        internal static string EnterHeaderString {
            get {
                return ResourceManager.GetString("EnterHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delegated.
        /// </summary>
        internal static string ExecutorString_Delegated {
            get {
                return ResourceManager.GetString("ExecutorString_Delegated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Me.
        /// </summary>
        internal static string ExecutorString_Me {
            get {
                return ResourceManager.GetString("ExecutorString_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !!! EXPIRED !!!.
        /// </summary>
        internal static string ExpiresString {
            get {
                return ResourceManager.GetString("ExpiresString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thet group is already exists. Shoose another group name.
        /// </summary>
        internal static string GroupIsAlreadyExist_ErrorMessage {
            get {
                return ResourceManager.GetString("GroupIsAlreadyExist_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delegated Tasks.
        /// </summary>
        internal static string GroupsOfDelegatedTasks {
            get {
                return ResourceManager.GetString("GroupsOfDelegatedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Tasks.
        /// </summary>
        internal static string GroupsOfMyTasks {
            get {
                return ResourceManager.GetString("GroupsOfMyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Header.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete Task?.
        /// </summary>
        internal static string Is_ShouldDeleteThatTask_ {
            get {
                return ResourceManager.GetString("Is ShouldDeleteThatTask?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is that Task completed?.
        /// </summary>
        internal static string IsTaskCompleted_RequestWindow {
            get {
                return ResourceManager.GetString("IsTaskCompleted_RequestWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add from file....
        /// </summary>
        internal static string Menu_AddFromFile {
            get {
                return ResourceManager.GetString("Menu_AddFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Executor....
        /// </summary>
        internal static string NewTaskExecutor_EmptyString {
            get {
                return ResourceManager.GetString("NewTaskExecutor_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        internal static string RussianLanguage {
            get {
                return ResourceManager.GetString("RussianLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We&apos;ve got trouble during saving data....
        /// </summary>
        internal static string SavingErrorMessage {
            get {
                return ResourceManager.GetString("SavingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Completed Tasks:.
        /// </summary>
        internal static string ShowCompletedTasksString {
            get {
                return ResourceManager.GetString("ShowCompletedTasksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expired Tasks:.
        /// </summary>
        internal static string ShowExpiredTasksString {
            get {
                return ResourceManager.GetString("ShowExpiredTasksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Urgently.
        /// </summary>
        internal static string TaskContext_UrgencyCheckBoxMark {
            get {
                return ResourceManager.GetString("TaskContext_UrgencyCheckBoxMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note Content.
        /// </summary>
        internal static string TaskNoteContentButton {
            get {
                return ResourceManager.GetString("TaskNoteContentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tasks:.
        /// </summary>
        internal static string TaskPanelExpanderHeader {
            get {
                return ResourceManager.GetString("TaskPanelExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !!! Urgent !!!.
        /// </summary>
        internal static string TaskUrgencyMark {
            get {
                return ResourceManager.GetString("TaskUrgencyMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10 min.
        /// </summary>
        internal static string timeRange_10Min {
            get {
                return ResourceManager.GetString("timeRange_10Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 15 min.
        /// </summary>
        internal static string timeRange_15Min {
            get {
                return ResourceManager.GetString("timeRange_15Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 Hour.
        /// </summary>
        internal static string timeRange_1Hour {
            get {
                return ResourceManager.GetString("timeRange_1Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 30 min.
        /// </summary>
        internal static string timeRange_30Min {
            get {
                return ResourceManager.GetString("timeRange_30Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5 min.
        /// </summary>
        internal static string timeRange_5Min {
            get {
                return ResourceManager.GetString("timeRange_5Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Today:.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tomorrow:.
        /// </summary>
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Tasks:.
        /// </summary>
        internal static string TotalTasksString {
            get {
                return ResourceManager.GetString("TotalTasksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Who:.
        /// </summary>
        internal static string WhoString {
            get {
                return ResourceManager.GetString("WhoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The app has been minimised. Click the tray icon to show.
        /// </summary>
        internal static string WindowMinimizedAnnounceNotification {
            get {
                return ResourceManager.GetString("WindowMinimizedAnnounceNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
